#file: noinspection YAMLSchemaValidation
name: Testing Actions

on:
 #workflow_dispatch: # add option for manuel workflow trigger
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Slack commit message and sha
        run: >
          curl -X POST -H 'Content-type: application/json'
          --data '{"text":"Push detected :github: https://github.com/filipstojakovic/github-actions-demo/commit/${{ github.sha }} - ${{ github.event.head_commit.message }}"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Main checkout
        uses: actions/checkout@v4

      - name: Send Slack Message
        run: >
          curl -X POST -H 'Content-type: application/json'
          --data '{"text":"Deployment started :progress_bar: :fingerscrossed:"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Send Slack Message
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":":maven: Building with Maven"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Run test and build
        run: mvn clean install

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
      - name: Send Slack Message
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":":docker: Building and Push to DockerHub"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: filipstojakovic/demo-app
          tags: ${{ github.sha }}, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Send Slack Message
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":":docker: Image pushed to https://hub.docker.com/repository/docker/filipstojakovic/demo-app"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Slack Message
        if: always() # run this step no matter what
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            emoji=":white_check_mark:"
          else
            emoji=":x:"
          fi
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"Job finished with status: $emoji ${{ job.status }}\"}" \
            "${{ secrets.SLACK_WEBHOOK_URL }}"
